### ISSUE TITLE
小问题，user_id是指？

### ISSUE THREAD

**Issue by zhiqihuang** [humiaozuzu/wechat-explorer#2]
微信号？ QQ号？还是？MD5是无法decode的，还望指明，谢谢

**Comment by zhiqihuang** [comment]
nvm, 我好像知道了

**Comment by atav32** [comment]
wait, @arcaneaura what's the answer haha 😂

**Comment by soyaine** [comment]
@zeeqy 你好，这个 nvm 是指什么？

**Comment by baozijianke** [comment]
@soyaine  never mind

**Comment by marekyggdrasil** [comment]
so how to get the `user_id`, @zeeqy ?
